name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  collection:
  intl:
  logging:
  meta:
  vector_math:

dev_dependencies:
  mockito:
  test:
