name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_common:
    git:
      url: https://github.com/deckerst/flutter_google_charts.git
      ref: aves
      path: charts_common
  collection:
  intl:
  logging:
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  test:
