name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_common:
    path: ../charts_common/
  collection:
  intl:
  logging:
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  test:
